Fix bad case mappings reference
Broken in "standardized this.data.caseManagement access"
commit:60822f646a01c23c7d31226a8a11bb644a203045

Bug revealed by test:
  1) Vellum core
       save conflict resolution logic
         should not send sha1 checksum with full form post:
     SyntaxError: Unexpected token u in JSON at position 0
      at JSON.parse (<anonymous>)
      at _instance.onFormSave (webpack-internal:///./src/caseManagement.js:577:38)
      at _instance.<computed> [as onFormSave] (webpack-internal:///./src/base.js:60:29)
      at Object.success (webpack-internal:///./src/core.js:2378:23)
      at Object.options.success (webpack-internal:///./lib/SaveButton.js:67:29)
      at Object.ajax (webpack-internal:///./lib/SaveButton.js:83:29)
      at _instance.fn.send (webpack-internal:///./src/core.js:2347:35)
      at Context.eval (webpack-internal:///./tests/core.js:625:20)